---
- name: Install and configure central system security services (e.g. LDAP server)
  hosts: all
  vars_files:
    - vars/external_vars.yml
  become: yes
  become_method: sudo
  tasks:
    - name: Fix internal network
      include: tasks/fix_internal_network.yml

    - name: Clear out tmp files
      include: tasks/clean_tmp_files.yml

    - name: Check that environment variables have OK values
      include: tasks/check_env_vars.yml

    - name: Populate /etc/hosts file with hostname entries for all VMs
      include: tasks/set_hosts.yml

    - name: Set the Ceritifcate/LDAP Distinguished Names
      include: tasks/set_distinguished_names.yml

    - name: Install and configure OpenLDAP
      include: tasks/install_openldap.yml
      when: client_auth_method == "ldap"

    - name: Install and configure Kerberos KDC
      include: tasks/install_kerberoskdc.yml
      when: client_auth_method == "kerberos"

    - name: Install and configure PyKMIP
      include: tasks/install_pykmip.yml
      when: encryptdb_enabled and encryptdb_key_loc == 'kmip'
      
    - name: Generate TLS/SSL CA & server key/cert files for encryption over the wire
      include: tasks/generate_server_keys.yml
      when: ssl_enabled or client_auth_method == 'cert'

